speed_sector_tuner:
  ros__parameters:
    save_params: false
    phase_multiplier: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 97
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 98
      end: 130
      scaling: 0.8
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 131
      end: 232
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 233
      end: 270
      scaling: 0.8
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 271
      end: 332
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 333
      end: 401
      scaling: 1.0
      only_FTG: false
      no_FTG: false
