speed_sector_tuner:
  ros__parameters:
    save_params: false
    global_limit: 1.0
    n_sectors: 4
    Sector0:
      start: 0
      end: 115
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 116
      end: 171
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 172
      end: 289
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 290
      end: 351
      scaling: 1.0
      only_FTG: false
      no_FTG: false
